# Generated by Django 4.2.7 on 2023-11-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_reg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25)),
                ('mobileno', models.IntegerField()),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
