# Generated by Django 4.2.7 on 2023-11-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_js_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_reg',
            name='id',
        ),
        migrations.AlterField(
            model_name='emp_reg',
            name='email',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
